In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
df_nci = pd.read_csv('/content/drive/MyDrive/2026 - 2/DEFI II/TALLER BTC/NCI.csv')
display(df_nci.head())

         Date  Close/Last     Open     High      Low
0  08/24/2026     3802.51  3819.58  3860.19  3763.95
1  08/21/2026     3799.52  3681.85  3801.65  3658.38
2  08/20/2026     3536.88  3446.36  3540.44  3410.09
3  08/19/2026     3339.38  3076.72  3366.54  3069.02
4  08/18/2026     3053.88  3030.00  3072.57  3026.81

### Añadir nuevas columnas al dataset

In [4]:
import numpy as np

In [5]:
# 1. Retornos Logarítmicos
df_nci['Log_Returns'] = np.log(df_nci['Close/Last'] / df_nci['Close/Last'].shift(1))

# Mostrar las primeras filas con las nuevas columnas
print("DataFrame con las nuevas columnas:")
display(df_nci.head())

DataFrame con las nuevas columnas:

         Date  Close/Last     Open     High      Low  Log_Returns
0  08/24/2026     3802.51  3819.58  3860.19  3763.95          NaN
1  08/21/2026     3799.52  3681.85  3801.65  3658.38    -0.000787
2  08/20/2026     3536.88  3446.36  3540.44  3410.09    -0.071630
3  08/19/2026     3339.38  3076.72  3366.54  3069.02    -0.057460
4  08/18/2026     3053.88  3030.00  3072.57  3026.81    -0.089372

### Crear una tabla aparte con estadísticas

In [6]:
# Calcular las métricas solicitadas

# Retorno promedio diario
mean_daily_return = df_nci['Log_Returns'].mean()

# Retorno acumulado
cumulative_return = (df_nci['Close/Last'].iloc[-1] / df_nci['Close/Last'].iloc[0]) - 1

# Retorno anualizado (asumiendo 252 días hábiles en un año para retornos logarítmicos)
annualized_return = mean_daily_return * 252

# Desviación estándar de retornos diarios
std_daily_returns = df_nci['Log_Returns'].std()

# Volatilidad anualizada
annualized_volatility = std_daily_returns * np.sqrt(252)

# Varianza de retornos diarios
variance_daily_returns = df_nci['Log_Returns'].var()

# Asimetría de retornos diarios
skewness_daily_returns = df_nci['Log_Returns'].skew()

# Curtosis de retornos diarios
kurtosis_daily_returns = df_nci['Log_Returns'].kurt()

# Crear un DataFrame para las estadísticas
stats_df = pd.DataFrame({
    'Métrica': [
        'Retorno promedio diario',
        'Retorno acumulado',
        'Retorno anualizado',
        'Desviación estándar de retornos diarios',
        'Volatilidad anualizada',
        'Varianza de retornos diarios',
        'Asimetría de retornos diarios',
        'Curtosis de retornos diarios'
    ],
    'Valor': [
        mean_daily_return,
        cumulative_return,
        annualized_return,
        std_daily_returns,
        annualized_volatility,
        variance_daily_returns,
        skewness_daily_returns,
        kurtosis_daily_returns
    ]
})

# Mostrar la tabla de estadísticas
print("Tabla de Estadísticas de Retornos de XBI:")
display(stats_df)

Tabla de Estadísticas de Retornos de XBI:

                                   Métrica     Valor
0                  Retorno promedio diario -0.000192
1                        Retorno acumulado -0.213851
2                       Retorno anualizado -0.048391
3  Desviación estándar de retornos diarios  0.034884
4                   Volatilidad anualizada  0.553767
5             Varianza de retornos diarios  0.001217
6            Asimetría de retornos diarios  0.544773
7             Curtosis de retornos diarios  6.147250

In [7]:
df_nci.to_csv('df_nci.csv', index=True)
stats_df.to_csv('nci_stats.csv', index=False)
print("df_xbi.csv and xbi_stats.csv have been downloaded.")

df_xbi.csv and xbi_stats.csv have been downloaded.